name: Update profile metrics
on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.yml"

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}
          user: ernes7
          repositories_affiliations: owner, collaborator, organization_member
          template: classic
          base: activity, repositories, metadata
          base_skip: header
          
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: no
          plugin_habits_from: 200
          
          output_action: commit
          committer_branch: master
          filename: metrics.svg
          
          output_action: commit
          committer_branch: master
          filename: metrics.svg
